name: Matrix Service

on:
    push: 
        branches: ["main"]

jobs:
    ignore-check:
        runs-on: ubuntu-latest
        outputs:
            build_matrix: ${{ steps.check.outputs.build_matrix }}
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Run the script
              id: check
              run: |
                apps=($(ls apps))
                build_matrix=$(printf '%s\n' "${apps[@]}" | jq -R . | jq -cs .)
                echo "build_matrix=$build_matrix" >> "$GITHUB_OUTPUT"

    update-tag:
        runs-on: ubuntu-latest
        needs: 
          - ignore-check

        steps:
            - name: Clone Gitops repo, update, and push
              run: |
                git clone https://github.com/Krishil-Jayswal/Gitops.git

                cd Gitops

                git config user.name "GitHub Actions Bot"
                git config user.email "actions@github.com"

                echo '${{ needs.ignore-check.outputs.build_matrix }}' | jq -r '.[]' | while read -r app_name; do
                  sed -i "s|image: jkrishil/ci-cd-monorepo-${app_name}:.*|image: jkrishil/ci-cd-monorepo-${app_name}:${{ github.sha }}|" "ci-cd-monorepo/${app_name}/deployment.yml"
                  cat "ci-cd-monorepo/$app_name/deployment.yml"
                done
