name: Testing for the Workflow
on:
    push:
        branches:
            "main"

jobs:
    print_test_passed:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
              
            - name: Run Turbo Ignore
              run: |
                echo "Running script"

                set +e
                npx turbo-ignore web
                exit_code=$?
                set -e

                echo "Exit code: $exit_code"

                if [ $exit_code -eq 0]; then
                  echo "Early exit"
                  exit 0
                else 
                  echo "Early exit failed"
                fi
            - name: Print Passes
              run: echo "Test passed"
            - name: Print Branch
              run: echo "Current branch ${{ github.ref }}"