name: Testing for the Workflow
on:
    push:
        branches:
            "main"

jobs:
    print_test_passed:
        runs-on: ubuntu-latest
        steps:
            - name: Print Passes
              run: echo "Test passed"
            - name: Print Branch
              run: echo "Current branch ${{ github.ref }}"