name: Testing for the Workflow
on:
    push:
        branches:
            "main"

jobs:
    ignore_test:
        runs-on: ubuntu-latest
        outputs:
          status_code: ${{ steps.check.outputs.earlyExit }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
              
            - name: Run Turbo Ignore
              id: check
              run: |
                echo "Running script"

                set +e
                npx turbo-ignore web
                exit_code=$?
                set -e

                echo "Exit code: $exit_code"

                if [ $exit_code -eq 0 ]; then
                  echo "Early exit"
                  echo "earlyExit=0" >> $GITHUB_OUTPUT
                else 
                  echo "Early exit failed"
                  echo "earlyExit=1" >> $GITHUB_OUTPUT
                fi
    build_test:
        runs-on: ubuntu-latest
        needs: ignore_test
        if: needs.ignore_test.outputs.status_code != 0
        steps:
            - name: Build
              run: echo "Building"